### ISSUE TITLE
Deps updates?

### ISSUE THREAD

**Issue by akhedrane** [appitventures/Forret#13]
Hi, 
i would thank you for this great job guys.

i 've 2 points:
- there is a lot of updates in deps such as dingo/api and ouath2-server.
- zizako/confide+entrust packages looks better for this pack.

**Comment by lagbox** [comment]
If you guys want I can push up to my repository a version with the latest deps and some adjustments.

**Comment by Jnom** [comment]
yes if you can, cuz there is a major updates.
